In [1]:
uso_cpu = [
[20, 25, 40, 50, 45, 60, 55, 35, 70, 65],
[30, 35, 50, 60, 40, 55, 60, 45, 50, 55],
[15, 20, 30, 25, 35, 40, 45, 50, 55, 60],
[10, 15, 25, 35, 45, 50, 55, 60, 65, 70],
]

In [2]:
import pandas as pd

In [18]:
df = pd.DataFrame(uso_cpu)

df.columns = ['1h', '2h', '3h', '4h', '5h', '6h', '7h', '8h', '9h', '10h']

df

   1h  2h  3h  4h  5h  6h  7h  8h  9h  10h
0  20  25  40  50  45  60  55  35  70   65
1  30  35  50  60  40  55  60  45  50   55
2  15  20  30  25  35  40  45  50  55   60
3  10  15  25  35  45  50  55  60  65   70

In [19]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.3.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (7.2 kB)
Downloading mysql_connector_python-9.3.0-cp311-cp311-manylinux_2_28_x86_64.whl (33.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.9/33.9 MB 30.4 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.3.0

ProgrammingError: 1049 (42000): Unknown database 'prova'

In [24]:
import mysql.connector

mydb = mysql.connector.connect(
  host="database-3.c71vmslgnnmk.us-east-1.rds.amazonaws.com",
  user="admin",
  password="senai115",
  database="database-3"
)

mycursor = mydb.cursor()

mycursor.execute("CREATE TABLE tabela (Nome VARCHAR(255), Endereco VARCHAR(255))")

mycursor.execute("SHOW COLUMNS FROM tabela")

ProgrammingError: 1049 (42000): Unknown database 'database-3'